# Generated by Django 6.0 on 2026-03-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_donationclaim_is_distributed_user_total_carbon_saved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationclaim',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Why did the driver drop the job?', null=True),
        ),
        migrations.AddField(
            model_name='donationclaim',
            name='condition_upon_arrival',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('ACCEPTABLE', 'Acceptable'), ('SPOILED', 'Spoiled/Unusable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='donationclaim',
            name='delivery_distance_km',
            field=models.FloatField(blank=True, help_text='Stored statically for historical analysis', null=True),
        ),
        migrations.AddField(
            model_name='donationclaim',
            name='time_delivered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationclaim',
            name='time_picked_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationclaim',
            name='was_rejected_by_ngo',
            field=models.BooleanField(default=False, help_text='Did the NGO refuse the food at the door?'),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='estimated_value_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Economic value saved', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='estimated_weight_kg',
            field=models.FloatField(blank=True, help_text='Used for load-balancing bikes vs cars', null=True),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='food_category',
            field=models.CharField(choices=[('COOKED_MEAL', 'Cooked Meals (Buffet/Restaurant)'), ('RAW_PRODUCE', 'Raw Produce (Vegetables/Fruits)'), ('BAKED_GOODS', 'Baked Goods (Bread/Pastries)'), ('PACKAGED', 'Packaged/Canned Food')], default='COOKED_MEAL', max_length=20),
        ),
        migrations.AddField(
            model_name='fooddonation',
            name='perishability_level',
            field=models.CharField(choices=[('HIGH', 'High (Spoils in < 4 hours)'), ('MEDIUM', 'Medium (Spoils in < 24 hours)'), ('LOW', 'Low (Lasts for days)')], default='HIGH', max_length=10),
        ),
        migrations.AlterField(
            model_name='donationclaim',
            name='delivery_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='donationclaim',
            name='food',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='main_app.fooddonation'),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='food_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='prepared_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=20),
        ),
    ]
