# Generated by Django 6.0 on 2026-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_donationclaim_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Standard Restaurant'), ('BAKERY', 'Bakery / Cafe'), ('HOTEL', 'Hotel / Buffet'), ('CATERER', 'Event Caterer'), ('GROCERY', 'Grocery / Supermarket')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Critical for predicting delivery surges.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='peak_surplus_day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday'), ('EVERYDAY', 'Consistent Every Day'), ('WEEKEND', 'Weekends')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seating_capacity',
            field=models.IntegerField(blank=True, help_text='Correlates to max surplus volume.', null=True),
        ),
    ]
