# Generated by Django 6.0 on 2026-03-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_user_business_type_user_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, choices=[('STUDENT', 'Student'), ('PROFESSIONAL', 'Working Professional'), ('FREELANCE', 'Freelancer / Gig Worker'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_shift',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning (8 AM - 12 PM)'), ('AFTERNOON', 'Afternoon (12 PM - 4 PM)'), ('EVENING', 'Evening (4 PM - 8 PM)'), ('NIGHT', 'Late Night (8 PM onwards)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('BIKE', 'Motorcycle / Scooter'), ('BICYCLE', 'Bicycle'), ('CAR', 'Car / Van'), ('WALK', 'Walking')], max_length=20, null=True),
        ),
    ]
